name: build-kernel (DO NOT RUN ME STANDALONE)

on:
    workflow_call:
        inputs:
          device:
            type: string
            required: true
          device_name:
            type: string
            required: true
        secrets:
          TELEGRAM_BOT_TOKEN:
            required: true
          TELEGRAM_CHAT_ID:
            required: true

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    env:
      DEVICE: ${{ inputs.device }}
      DEVICE_NAME: ${{ inputs.device_name }}

    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Set Timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "America/Sao_Paulo"

      - name: Setting up the environment
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Set Build Start Time
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: Run build script
        run: |
          export DEVICE=${{ env.DEVICE }}
          ./build.sh

      - name: Set Build End Time
        run: echo "END_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: Calculate Build Duration
        run: |
          duration=$((END_TIME - START_TIME))
          minutes=$((duration / 60))
          seconds=$((duration % 60))
          echo "BUILD_DURATION=${minutes}m ${seconds}s" >> $GITHUB_ENV

      - name: Set ZIP File Path
        run: echo "zip_file=$(ls not-CI-*.zip | head -n1)" >> $GITHUB_ENV
     
      - name: Set release tag
        run: echo "RELEASE_TAG=kernel-${DEVICE}-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
        
      - name: Prepare Release Info
        run: |
           echo "KERNEL_VERSION=$(cat out/include/config/kernel.release)" >> $GITHUB_ENV
           echo "BUILD_DATE=$(date +'%d %B %Y')" >> $GITHUB_ENV
           echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: "Kernel Build for ${{ env.DEVICE_NAME }}"
          body: |
            Localversion: ${{ env.KERNEL_VERSION }}
            Clang version: kernel.org LLVM 22.1.3
            Build Date: ${{ env.BUILD_DATE }}
            Build commit hash: ${{ env.COMMIT_HASH }}
            KernelSU version: 32468 / 3.2.4-15
            SusFS version: v2.1.0
            SELinux: Enforcing
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.zip_file }}
          asset_name: "kernel-${{ env.DEVICE }}.zip"
          asset_content_type: application/zip
